### ISSUE TITLE
Web sẽ gầy

### ISSUE THREAD

**Issue by mnguyen081002** [Khiem27/jobboard#1]
Lag quas chiu ko noi, 1 sao. App nhu qq
![image](https://user-images.githubusercontent.com/76799726/160234450-2f298afa-ec82-4b5a-8bbb-84bdfd8c28bc.png)

**Comment by Khiem27** [comment]
Back end như cc, xin lỗi quý khách vì sự bất tiện này

Vào 16:58, Th 7, 26 thg 3, 2022 Titus Nguyên ***@***.***> đã
viết:
